name: MACOS_Binary

on:
    push:
        tags:
            - '*'

jobs:
    build:
    
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v3
        - name: Build
          run: make


        - uses: actions/upload-artifact@v4
          with:
            compression-level: 0
            name: MACOS
            path: ./Final_Build/CLI_Timer
        
        