name: MACOS_Upload_Binary

on:
    push:
        tags:
            - '*'

jobs:
    build:
    
        runs-on: macos-latest
        steps:
        - uses: actions/checkout@v3
        
        - name: Build
          run: make Final_Name=CLI_Timer_MacOs

        - name: upload to release
          env:
            GH_TOKEN: ${{ github.token }}
          run: gh release upload ${{github.ref_name}} ./build/CLI_Timer_MacOs