name: UBUNTU_Upload_Binary

on:
    push:
        tags:
            - '*'

jobs:
    build:
    
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v3
        
        - name: Build
          run: make Final_Name=CLI_Timer_Linux

        - name: upload to release
          env:
            GH_TOKEN: ${{ github.token }}
          run: gh release upload ${{github.ref_name}} ./Final_Build/CLI_Timer_Linux
        
        
        